  version: '3.8'

  services:
    # frontend:
    #   build:
    #     context: ./place-map-app
    #   ports:
    #     - "3000:3000"
    #   depends_on:
    #     - backend

    # backend:
    #   build:
    #     context: ./backend
    #   ports:
    #     - "3001:3001"
    #   depends_on:
    #     - mongo

    mongo:
      image: mongo:4.2
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db

  volumes:
    mongo-data: